name: Lets Start NekoRobot
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "and user not in [777000, 1087968824]"
          replace: "and user not in [777000, 1087968824, 931530251]"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'NekoRobot'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Rachit-Pal
          commit_user_email: 83032665+Rachit-Pal@users.noreply.github.com
          commit_author: Rachit-Pal <83032665+Rachit-Pal@users.noreply.github.com>
